### ISSUE TITLE
adblock

### ISSUE THREAD

**Issue by csgillespie** [WhoTargetsMe/Who-Targets-Me#18]
If a user has adblock (or friends) installed. Will that stop results from being shown?

**Comment by stunningpixels** [comment]
Hi,

If it blocks adverts on the facebook newsfeed - then yes.

**Comment by csgillespie** [comment]
Do (can you) record if a user has adblock installed. That way you could exclude them from your analysis

**Comment by mariocimet** [comment]
@csgillespie [These](http://stackoverflow.com/questions/6293498/check-whether-user-has-a-chrome-extension-installed) people are offering a way to do it:

> Have your Chrome extension look for a specific DIV or other element on your page, with a very specific ID.

For example:

<div id="ExtensionCheck_JamesEggersAwesomeExtension"></div>
Do a getElementById and set the innerHTML to the version number of your extension or something. You can then read the contents of that client-side.

Again though, you should use a direct method if there is one available.

EDIT: Direct method found!!

Use the connection methods found here: https://developer.chrome.com/extensions/extension#global-events

Untested, but you should be able to do...

var myPort=chrome.extension.connect('yourextensionid_qwerqweroijwefoijwef', some_object_to_send_on_connect);
