### ISSUE TITLE
code reuse

### ISSUE THREAD

**Issue by vecna** [WhoTargetsMe/Who-Targets-Me#22]
Hi, this is not an "issue", but rather a simple notice

If you look at `promotedInfo` `promotedLink` `promotedTitle` parsers here: https://github.com/tracking-exposed/facebook/tree/master/parsers you might find some w3c selector who might be reused by you.

I'm afraid here is happen a big duplication of scope, if we know each other earlier, you could have use fbtrex extension and download all the promoted posts as a CSV (it is a feature supported by some months)

**Comment by janbaykara** [comment]
HI @vecna. We're discussing how we can integrate this, thanks for the notice.

Thankfully, we've lost no opportunities - we store the advert HTML and could retroactively parse it to get this CSV data :)

**Comment by vecna** [comment]
Good, but still, my and the team are small, your team has done an effort to develop a single-task platform... that's not the optimal way 

These kind of initiatives are small, unfunded and exposed to engineering, humans and sustainability problems. it is far better if we can collaborate and separate roles.

If you would have used fbtrex, you could be more dedicated in analyzing the data rather than doing a collection platform. Considering your campaign how much was extensive, I would have to struggle less in doing announcement like this ( https://medium.com/@trackingexposed/uk17-election-and-facebook-algorithms-call-for-a-group-analysis-6ad84d37eca0 ) Plus, someone other might have done analysis on the public post (not just adv) and how the Facebook algorithm differentiate the posts.
